// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Link");

function handleClick(href, target, $$event, isExternal) {
  var exit = 0;
  if (isExternal !== undefined && isExternal) {
    return /* () */0;
  } else {
    exit = 1;
  }
  if (exit === 1) {
    var exit$1 = 0;
    if (target !== undefined && target !== "") {
      return /* () */0;
    } else {
      exit$1 = 2;
    }
    if (exit$1 === 2) {
      if ($$event.defaultPrevented) {
        return 0;
      } else {
        $$event.preventDefault();
        return ReasonReact.Router[/* push */0](href);
      }
    }
    
  }
  
}

function safeguardRelIfExternalLink(isExternal, rel) {
  var exit = 0;
  if (isExternal !== undefined && isExternal && rel === undefined) {
    return "noopener noreferrer";
  } else {
    exit = 1;
  }
  if (exit === 1) {
    if (rel !== undefined) {
      return rel;
    } else {
      return "";
    }
  }
  
}

function make(href, className, target, isExternal, rel, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var tmp = {
                className: "link " + Js_option.getWithDefault("link-default", className),
                href: href,
                rel: safeguardRelIfExternalLink(isExternal, rel),
                onClick: Curry._1(self[/* handle */0], (function ($$event, param) {
                        return handleClick(href, target, $$event, isExternal);
                      }))
              };
              if (target !== undefined) {
                tmp.target = Caml_option.valFromOption(target);
              }
              return ReactDOMRe.createElementVariadic("a", Caml_option.some(tmp), children);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.handleClick = handleClick;
exports.safeguardRelIfExternalLink = safeguardRelIfExternalLink;
exports.make = make;
/* component Not a pure module */
