// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_option = require("bs-platform/lib/js/js_option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var revealAfter = Css.style(/* :: */[
      Css.display(/* block */888960333),
      /* :: */[
        Css.maxHeight(/* zero */-789508312),
        /* :: */[
          Css.overflow(/* hidden */-862584982),
          /* :: */[
            Css.transition(500, undefined, undefined, "max-height"),
            /* [] */0
          ]
        ]
      ]
    ]);

var revealAfterOpen = Css.style(/* :: */[
      Css.maxHeight(/* `vw */[
            26433,
            1000
          ]),
      /* [] */0
    ]);

function changeText(status) {
  if (status) {
    return "";
  } else {
    return ">";
  }
}

var component = ReasonReact.reducerComponent("RevealRe");

function make(before, after, className, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* show */0];
              var extraClass = match ? revealAfterOpen : "";
              return React.createElement("div", {
                          className: "reveal " + Js_option.getWithDefault("", className)
                        }, React.createElement("div", {
                              key: "before",
                              className: "reveal-before",
                              dangerouslySetInnerHTML: {
                                __html: before
                              }
                            }), React.createElement("div", {
                              key: "after",
                              className: "reveal-after " + (revealAfter + (" " + extraClass)),
                              dangerouslySetInnerHTML: {
                                __html: after
                              }
                            }), React.createElement("button", {
                              onClick: (function (_e) {
                                  return Curry._1(self[/* send */3], /* Setshow */[!self[/* state */1][/* show */0]]);
                                })
                            }, self[/* state */1][/* show */0] ? "" : ">"));
            }),
          /* initialState */(function (param) {
              return /* record */[/* show */false];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, param) {
              return /* Update */Block.__(0, [/* record */[/* show */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.revealAfter = revealAfter;
exports.revealAfterOpen = revealAfterOpen;
exports.changeText = changeText;
exports.component = component;
exports.make = make;
/* revealAfter Not a pure module */
