// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var BaseSlider = require("./BaseSlider.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("ControlledSlider");

function make(initialSlide, slides, config, className, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, BaseSlider.make(slides, self[/* state */1][/* slide */0], config, "controlled-slider " + Js_option.getWithDefault("controlled-slider-default", className), /* array */[
                              React.createElement("div", {
                                    className: "slider-controls"
                                  }, React.createElement("div", {
                                        className: "slide-left",
                                        onClick: (function (_e) {
                                            return Curry._1(self[/* send */3], /* PrevSlide */1);
                                          })
                                      }), React.createElement("div", {
                                        className: "slide-right",
                                        onClick: (function (_e) {
                                            return Curry._1(self[/* send */3], /* NextSlide */0);
                                          })
                                      })),
                              React.createElement("div", {
                                    className: "slider-bullets-container"
                                  }, React.createElement("div", {
                                        className: "slider-bullets"
                                      }, Belt_List.toArray(Belt_List.mapWithIndex(slides, (function (index, slide) {
                                                  var match = slide[/* slideNumber */1] === self[/* state */1][/* slide */0];
                                                  return React.createElement("div", {
                                                              key: "bullet-" + String(index),
                                                              className: "slider-bullet" + (
                                                                match ? " slider-bullet-current" : ""
                                                              ),
                                                              onClick: (function (_e) {
                                                                  return Curry._1(self[/* send */3], /* GoToSlide */[index]);
                                                                })
                                                            });
                                                })))))
                            ]));
            }),
          /* initialState */(function (param) {
              return /* record */[/* slide */initialSlide];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  if (state[/* slide */0] === 0) {
                    var match = config[/* loopSlides */1];
                    if (match) {
                      return /* Update */Block.__(0, [/* record */[/* slide */Belt_List.length(slides) - 1 | 0]]);
                    } else {
                      return /* NoUpdate */0;
                    }
                  } else {
                    return /* Update */Block.__(0, [/* record */[/* slide */state[/* slide */0] - 1 | 0]]);
                  }
                } else if (state[/* slide */0] === (Belt_List.length(slides) - 1 | 0)) {
                  var match$1 = config[/* loopSlides */1];
                  if (match$1) {
                    return /* Update */Block.__(0, [/* record */[/* slide */0]]);
                  } else {
                    return /* NoUpdate */0;
                  }
                } else {
                  return /* Update */Block.__(0, [/* record */[/* slide */state[/* slide */0] + 1 | 0]]);
                }
              } else {
                return /* Update */Block.__(0, [/* record */[/* slide */action[0]]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
