// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var pageStyle = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.maxHeight(Css.vh(100.0)),
          /* :: */[
            Css.height(/* `percent */[
                  -119887163,
                  100.0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var pageContentsStyle = Css.style(/* :: */[
      Css.overflow(Css.auto),
      /* :: */[
        Css.flex(1),
        /* [] */0
      ]
    ]);

var component = ReasonReact.statelessComponent("PageRe");

function mapPageEnd(pageEndArray, extraClass) {
  var match = Belt_List.length(pageEndArray);
  if (match !== 0) {
    return React.createElement("div", {
                key: extraClass,
                className: "page-end-container page-end-" + extraClass
              }, Belt_List.toArray(Belt_List.mapWithIndex(pageEndArray, (function (i, info) {
                          var tmp;
                          tmp = info.tag ? ReactDOMRe.createElementVariadic("div", {
                                  className: "page-end-children"
                                }, info[0]) : React.createElement("div", {
                                  className: "page-end-text"
                                }, info[0]);
                          return React.createElement("div", {
                                      key: String(i),
                                      className: "page-end page-end-" + String(i)
                                    }, tmp);
                        }))));
  } else {
    return null;
  }
}

function extraClasses(pageEnds) {
  var match = Belt_List.length(pageEnds[/* top */0]);
  var topClass = match !== 0 ? "page-has-top" : "";
  var match$1 = Belt_List.length(pageEnds[/* bottom */1]);
  var bottomClass = match$1 !== 0 ? "page-has-bottom" : "";
  return topClass + (" " + bottomClass);
}

function make(pageEnds, className, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var extraClasses$1 = extraClasses(pageEnds);
              return React.createElement("div", {
                          className: "page " + (extraClasses$1 + (" " + (Js_option.getWithDefault("page-default", className) + (" " + pageStyle))))
                        }, mapPageEnd(pageEnds[/* top */0], "top"), React.createElement("div", {
                              key: "children",
                              className: "page-content-container " + pageContentsStyle
                            }, ReactDOMRe.createElementVariadic("div", {
                                  className: "page-content"
                                }, children)), mapPageEnd(pageEnds[/* bottom */1], "bottom"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.pageStyle = pageStyle;
exports.pageContentsStyle = pageContentsStyle;
exports.component = component;
exports.mapPageEnd = mapPageEnd;
exports.extraClasses = extraClasses;
exports.make = make;
/* pageStyle Not a pure module */
