// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var React = require("react");
var Js_option = require("bs-platform/lib/js/js_option.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var popupBackground = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.height(Css.vh(100)),
        /* :: */[
          Css.width(Css.vw(100)),
          /* :: */[
            Css.position(Css.fixed),
            /* :: */[
              Css.top(Css.px(0)),
              /* :: */[
                Css.left(Css.px(0)),
                /* :: */[
                  Css.zIndex(-1000),
                  /* :: */[
                    Css.visibility(Css.hidden),
                    /* :: */[
                      Css.flexDirection(Css.column),
                      /* :: */[
                        Css.justifyContent(Css.center),
                        /* :: */[
                          Css.alignItems(Css.center),
                          /* :: */[
                            Css.backgroundColor(Css.rgba(0, 0, 0, 0)),
                            /* :: */[
                              Css.transition(500, undefined, undefined, "background-color"),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var popupBackgroundVisible = Css.style(/* :: */[
      Css.visibility(Css.visible),
      /* :: */[
        Css.zIndex(1000),
        /* :: */[
          Css.backgroundColor(Css.rgba(0, 0, 0, 0.25)),
          /* [] */0
        ]
      ]
    ]);

var popupContainer = Css.style(/* :: */[
      Css.backgroundColor(Css.white),
      /* [] */0
    ]);

var component = ReasonReact.statelessComponent("PopupRe");

function make(visible, pressClose, className, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "pop-up-background " + (popupBackground + (" " + ((
                                  visible ? "pop-up-visible" : "pop-up-hidden"
                                ) + (" " + ((
                                      visible ? popupBackgroundVisible : ""
                                    ) + (" " + Js_option.getWithDefault("popup-default", className))))))),
                          onClick: pressClose
                        }, React.createElement("div", {
                              className: "pop-up-container popup-delete-offer " + popupContainer,
                              onClick: (function (e) {
                                  e.stopPropagation();
                                  return /* () */0;
                                })
                            }, ReactDOMRe.createElementVariadic("div", {
                                  className: "pop-up-body"
                                }, children)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.popupBackground = popupBackground;
exports.popupBackgroundVisible = popupBackgroundVisible;
exports.popupContainer = popupContainer;
exports.component = component;
exports.make = make;
/* popupBackground Not a pure module */
